### ISSUE TITLE
Add article for champions story

### ISSUE THREAD

**Issue by sandilsranasinghe** [SpeechOlympiadXV/speecholympiadxv.github.io#31]
https://docs.google.com/document/d/18irYh-i0s-N74wBwusv9xbj1gOS-phR4TkQmrwQwhSU/edit?usp=sharing

**Comment by rajivaPavan** [comment]
I'll start working on this 
[Article 2 : Walk the Path of a Champion ](https://drive.google.com/file/d/1m7SYNIcM6JVXGjFMfgfBIZ-IYBfZ4JPY/view?usp=sharing)
