### ISSUE TITLE
Website adjustments 

### ISSUE THREAD

**Issue by oshanyalegama** [SpeechOlympiadXV/speecholympiadxv.github.io#41]
- [x] **Testimonials:**
This is about the testimonials on the home page which will only have an image of the speaker, a small text below with his or her name
and the content below it.
There is
Only if possible, create a carousel to with two testimonials in each turn as seen here:

![8f1697f5-d105-459a-9f21-f1d8101f5ded](https://user-images.githubusercontent.com/110217717/192139959-699c61fb-d2b1-4d24-9318-6d0b92f85904.jpg)

Else, have only 3 testimonials by excluding Asitha aiya without using a carousel. Add his testimonial in a later deployment by having a carousal.

- [x] **Walk the Path of a Champion**
Keep only the final paragraph(Being a champion.. onwards) in a box but bold the words "first runner-up" and "Champion of Speech Olympiad VIII in 2014" as they currently are.

- [x] **Home page**
Have the register now button be on the rightmost side of the header

**Comment by sandilsranasinghe** [comment]
register button to right in #39

**Comment by sandilsranasinghe** [comment]
Only the final paragraph in box, rest of the italic/highlighted parts will be back to normal in article path of champion
